# Generated by Django 3.1.5 on 2021-01-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_author_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.Catagory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
