# Generated by Django 3.1.5 on 2021-01-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210114_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(upload_to='profile pics'),
        ),
    ]
