# Generated by Django 3.1.5 on 2021-01-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210116_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='proflie_pic',
            field=models.ImageField(blank=True, default='user.svg', upload_to=''),
        ),
    ]
