# Generated by Django 3.1.5 on 2021-01-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210117_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='Post',
        ),
    ]
