# Generated by Django 3.1.5 on 2021-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210117_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.png', upload_to='profile pics'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='proflie_pic',
            field=models.ImageField(blank=True, default='user.png', upload_to=''),
        ),
    ]
