# Generated by Django 3.1.5 on 2021-01-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210117_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='proflie_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
