# Generated by Django 3.1.5 on 2021-01-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210117_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='proflie_pic',
        ),
    ]
