# Generated by Django 3.1.5 on 2021-01-17 14:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_comment_proflie_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
